### ISSUE TITLE
Focus field missing using $php -S localhost:8000

### ISSUE THREAD

**Issue by malvese** [flokosiol/kirby-focus#5]
I tried kirby-focus on a fresh starterkit, and got this error when I tried to edit an image (at URL `/panel/pages/projects/project-b/file/mountains․jpg/edit`):

```
The focus field is missing. Please add it to your installed fields or remove it from your blueprint
```

Looking at line 12, it seems the field path fails to register for some reason.

Also the previews are not generated when I set `c::set('thumbs.driver', 'focus');`

**Comment by medienbaecker** [comment]
Could you try to rename the plugin folder from "kirby-focus" to just "focus"?

**Comment by malvese** [comment]
Ha! Good point, thanks. No more error, but still no focus field when I edit image metadata. Cropping works though.

**Comment by medienbaecker** [comment]
And you've added the field to the blueprint "files" section like that?

```
files:
  fields:
    focus:
      type:        focus
      label:       Focus
```

**Comment by flokosiol** [comment]
Please check your blueprint settings. You need to add the field manually to your blueprint [like this](https://github.com/flokosiol/kirby-focus#2-blueprint).

**Comment by malvese** [comment]
I copid/pasted from the documentation, here's my blueprint:
```
files:
  sortable: true
  fields:
    focus:
      label: My Focus field
      type: focus
```

**Comment by medienbaecker** [comment]
That looks correct. And the page you're editing actually uses this blueprint? I can't see anything else that could be the cause.

**Comment by flokosiol** [comment]
What happens if you are adding other (Kirby default) fields to the files section of the blueprint? Do they appear as expected?

```
files:
  sortable: true
  fields:
    focus:
      label: My Focus field
      type: focus
    text:
      label: Some text
      type: text
```

**Comment by malvese** [comment]
Yes, if I use
```
  fields:
    focus:
      label: My Focus field
      type: focus
    test:
      label: test
      type: text
```

I can see my test field, but not the `focus` field.

**Comment by medienbaecker** [comment]
To record the preview GIF I downloaded a fresh starter kit myself and did the following things to install it:

1. Downloaded the **Kirby 2.3.0** starterkit
2. Put the `kirby-focus` folder in the `site/plugins` folder.
3. Renamed the folder to `focus`.
3. Added `c::set('thumbs.driver', 'focus');` to the `site/config/config.php` file.
4. Added the focus field to the `fields` section in all the relevant blueprints.

Since there's no issue with the actual cropping in your installation it can't even be something with the installed GD Library.

**Comment by flokosiol** [comment]
btw: I added the (re)naming of the plugin folder to the readme.

**Comment by malvese** [comment]
Thank you for your help! Update, with more oddities.
I reinstalled everything following @medienbaecker's steps.
* I initially used PHP's internal server (`$php -S localhost:8000`) and didn't see the `focus` field, as before.
* I tried with MAMP, now I see the field and can click on a point, but the focus point I set is not taken into account. The crop works but is always centered. I use:
```php
<?php echo $image->focusCrop(400); ?>
```
Then choose a point to the right of an image:
![image](https://cloud.githubusercontent.com/assets/193492/15712677/886bfcbe-2813-11e6-98f1-fab6caefe51c.png)

And the image is cropped smack in the middle:
![crop](https://cloud.githubusercontent.com/assets/193492/15712676/886ba318-2813-11e6-9c6f-d950d3e57f11.png)

**Comment by medienbaecker** [comment]
Alright, that's a step in the right direction.

You're cropping a square, this falsely ignores the focus point right now. See this issue: https://github.com/flokosiol/kirby-focus/issues/4

If you crop it to `<?php echo $image->focusCrop(400, 401); ?>` it should work.

**Comment by malvese** [comment]
Dammit! Hadn't seen this issue.
It helps, now the crop indeed moves.

I noticed:
* It doesn't work with something like `400,300`. 
I don't think this black strip on the left should be there?
![the-sea-400x300-5-44](https://cloud.githubusercontent.com/assets/193492/15713050/12465e74-2815-11e6-814f-4809cf6c63b9.jpg)
* With something like `300,400` it works, but the crop doesn't always include the focus point when it is near the side. Here I think I should see the corner of the image, including the whole bag?
![focus](https://cloud.githubusercontent.com/assets/193492/15713221/c87b6856-2815-11e6-8182-4899feda4612.jpg)

**Comment by malvese** [comment]
Well, that's actually another issue right? I should create another one.

**Comment by flokosiol** [comment]
The black strip on the right is another issue, that's right. I'm already working on this, though there's no official issue (yet). It's kind of a portrait-landscape-issue. Would you create another issue or shall I do?

Thanks for testing!

**Comment by malvese** [comment]
@flokosiol I'll create one, copy the information above and some more details.

**Comment by flokosiol** [comment]
**To sum it up:** 
There seem to be an issue, that the focus field isn't displayed while running `$php -S localhost:8000`

All there rest of this discussion will go on here …
https://github.com/flokosiol/kirby-focus/issues/6

**Comment by flokosiol** [comment]
Sorry, referenced the wrong issue in my commit message. Issue reopend.

**Comment by Andi-Lo** [comment]
I can also relate to that issue on win 10 using XAMPP.

**Comment by flokosiol** [comment]
Thanks for reporting. 

Since there has been a lot of different things discussed here in this topic, is it correct, that the image field to set the focus point is missing in your panel? Or are there any cropping issues?

Could you please set `c::set('debug',true)` in your `config.php` and check if you get any errors? Or is there anything tracked in your error_log? 

Regards. Flo.

**Comment by Andi-Lo** [comment]
The focus point is missing in the panel yes.

If I use 
```
    <?php 
	    // crop a rectangle of 300px x 200px
	    echo $image->focusCrop(300,200);
    ?>
```

I am getting the following errors:
- `Undefined variable: image in C:\xampp\htdocs\starterkit\site\templates\home.php on line 12`

- `Uncaught Error: Call to a member function focusCrop() on unknown in C:\xampp\htdocs\starterkit\site\templates\home.php on line 12`

If I don't use the focusCrop method to just see if there is a field in the backend panel I don't get any errors but I also can not see a focus field.

**Comment by flokosiol** [comment]
Before you can use the `focusCrop()` method you need a Kirby image object. In my example `$image` is just a placeholder for that. With the following code in your template file, you can grab the first image (automatically as an image object) and try to use the focusCrop:

```
<?php if ($page->hasImages()): ?>

  <?php $image = $page->images()->first() ?>
  <?php echo $image->focusCrop(200,100); ?>

<?php else: ?>
  
  No images have been uploaded to this page.

<?php endif; ?>
```

Could you please try that? You could also try to use a smaller image, e.g. 1000 x 1000px. 

If it does not work at all, it would be great, if you could paste your blueprint code here. Thanks.

**Comment by Andi-Lo** [comment]
Okay now I am getting a cropped Image. However the field is still missing in the panel.

My blueprint is as simple as this: 
```
title: Home
pages: true
files: true

fields:
  title:
    label: Title
    type:  text
  focus:
    label: My focus field
    type: focus
```

I don't get any console.log errors or anything. The DOM is also not showing any element that belongs to focus.

**Comment by flokosiol** [comment]
Alright. We're half way there.

The Focus field is a field used for every image, so it needs to be located at the [file fields](https://getkirby.com/docs/panel/blueprints/file-settings#file-fields). Try to change your blueprint like this:

```
title: Home
pages: true
files:
  fields:
    focus:
      label: My focus field
      type: focus
fields:
  title:
    label: Title
    type:  text
```

This should work :)

**Comment by Andi-Lo** [comment]
Ahhh yes how could I miss that :( ?

Thanks for your help :+1:  :)  works like a charm

**Comment by flokosiol** [comment]
Great. 

Regarding the original issue: I tested the focus field using `$php -S localhost:8000` and everything works fine. So I will close this issue.

**Comment by arnaudjuracek** [comment]
I'm having the same problem : the focus field is missing on the file panel when running on `php -S localhost:8888` on OSX 10.11.6.

When running on MAMP, the focus field is present.

**Comment by almone** [comment]
I'm having the same issue with php -S localhost:8888 on macOS 10.12.2.
Everything works great on Vagrant.

**Comment by flokosiol** [comment]
I will have a look at this again. Thanks for reporting.

**Comment by macx** [comment]
The same for me using grunt-php running under http://127.0.0.1:9000/: Is I set type: focus, the field is not visible in the panel.

**Comment by flokosiol** [comment]
I could reproduce the issue with `php -S localhost:8888` and it seems to be a problem with the filename encoding. I'll try to fix it as soon as possible.

**Comment by flokosiol** [comment]
Should be fixed now. 

The PHP CLI server encodes the `.` character differently. Because of this the `file` object could not be loaded and no image was found which could be displayed.

After digging deeper into Kirby's Panel code, I found a method which takes care of a proper filename decoding. As you can see [here](https://github.com/getkirby/panel/blob/master/app/src/panel/models/file.php#L34) it also replaces the `.` character for CLI server … seems to be known issue.

Due to another urgent issue (#19), I pushed it directly to the master and released v1.0.9 – hopefully everythings fine now.

**Comment by macx** [comment]
Still the same on my site with Version 1.0.9 (installed via Git Submodule). The focus field does not to appear. Change the field type back to `image` and I can see it.

**Comment by flokosiol** [comment]
@macx 
Strange?! I checked version 1.0.9 again with `grunt-php` and everything works fine for me.

Do you have the possibility to check it with a different server? If it works, we would be sure, that your [blueprint setup](https://github.com/flokosiol/kirby-focus#1-blueprint) is ok.

**Comment by macx** [comment]
@flokosiol I testet it with a fresh project. Installed as a git submodule (in `src/plugins/focus`) and used the following setup:

```yml
  cardImage:
    label: Main Image
    type: focus
    width: 1/2
```

As soon I use `focus`, the image element disappears from the Kirby Panel. Still using grunt-php at `http://127.0.0.1:900/`.

**Comment by macx** [comment]
Sorry @flokosiol: The whole time I did not read the manual properly. To me it was not clear to put the yml part into the files section and not the fields section itself. Now it's working, thank you.

**Comment by flokosiol** [comment]
Thanks for your reply.
Maybe I can check for this and output a message instead of doing nothing. I will give it a try …
